version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - REPO_URI=038462778050.dkr.ecr.us-east-1.amazonaws.com/nambath-ecs-app
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin $REPO_URI
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
  build:
    commands:
      - echo Building Docker image...
      - docker build -t $REPO_URI:$IMAGE_TAG .
  post_build:
    commands:
      - echo Pushing Docker image...
      - docker push $REPO_URI:$IMAGE_TAG
      - echo Writing imagedefinitions.json...
      - printf '[{"name":"nambath-app","imageUri":"%s"}]' $REPO_URI:$IMAGE_TAG > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
